# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
                    - name: Sauce Security Action
  # You may pin to the exact commit or the version.
  # uses: saucelabs/sauce-security-action@5008ddffb96db501fc71486cad3950304a73a2d5
  uses: saucelabs/sauce-security-action@v0.3.0
  with:
    # Sauce Labs user name.
    username: 
    # Sauce Labs API Key.
    accessKey: 
    # Url to the application under test.
    target: 
    # An url to an OpenAPI specification to help scan the full API.
    openapi: # optional
    # An url to a graphql schema to help scan the full API.
    graphql: # optional
    # Amount of severe vulnerabilities that are allowed to be discovered - if set to `-1` these will be ignored. (Default: 0)
    allowedSevereVulnerabilties: # optional, default is 0
    # Amount of medium vulnerabilities that are allowed to be discovered - if set to `-1` these will be ignored. (Default: 0)
    allowedMediumVulnerabilties: # optional, default is 0
    # Amount of low vulnerabilities that are allowed to be discovered - if set to `-1` these will be ignored. (Default: 0)
    allowedLowVulnerabilties: # optional, default is 0
    # Amount of informational vulnerabilities that are allowed to be discovered - if set to `-1` these will be ignored. (Default: 0)
    allowedInformationalVulnerabilties: # optional, default is -1
    # If set to true, this action will download Zap reports for you to attach to the job via actions/upload-artifact
    downloadReports: # optional
    # If set to true, this action will download all Sauce Labs job assets for you  to attach to the job via actions/upload-artifact
    downloadJobAssets: # optional
          
[![Deploy static content to Pages](https://github.com/WixAiDevPartner-org/FlowWeaver/actions/workflows/static.yml/badge.svg?branch=main&event=page_build)](https://github.com/WixAiDevPartner-org/FlowWeaver/actions/workflows/static.yml)
